### ISSUE TITLE
set theme to Harvard crimson

### ISSUE THREAD

**Issue by ernestguevarra** [rapidsurveys/okapi#29]
#A41034

```yaml
  bslib:
    bootswatch: united
    primary: "#A41034"

navbar:
  bg: primary
  type: light
```
